<?php
/**
 * AlertRefDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TimelightAi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * timelight
 *
 * This is the timelight api.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace TimelightAi;

/**
 * AlertRefDtoTest Class Doc Comment
 *
 * @category    Class
 * @description AlertRefDto
 * @package     TimelightAi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AlertRefDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AlertRefDto"
     */
    public function testAlertRefDto()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "source_id"
     */
    public function testPropertySourceId()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "criticity"
     */
    public function testPropertyCriticity()
    {
    }

    /**
     * Test attribute "shape"
     */
    public function testPropertyShape()
    {
    }

    /**
     * Test attribute "activity"
     */
    public function testPropertyActivity()
    {
    }

    /**
     * Test attribute "comment"
     */
    public function testPropertyComment()
    {
    }

    /**
     * Test attribute "day_activity"
     */
    public function testPropertyDayActivity()
    {
    }

    /**
     * Test attribute "better_model_name"
     */
    public function testPropertyBetterModelName()
    {
    }

    /**
     * Test attribute "better_model_value"
     */
    public function testPropertyBetterModelValue()
    {
    }

    /**
     * Test attribute "better_model_color"
     */
    public function testPropertyBetterModelColor()
    {
    }

    /**
     * Test attribute "better_model_activity"
     */
    public function testPropertyBetterModelActivity()
    {
    }

    /**
     * Test attribute "better_model_top_tolerance"
     */
    public function testPropertyBetterModelTopTolerance()
    {
    }

    /**
     * Test attribute "better_model_bottom_tolerance"
     */
    public function testPropertyBetterModelBottomTolerance()
    {
    }

    /**
     * Test attribute "closest_model_name"
     */
    public function testPropertyClosestModelName()
    {
    }

    /**
     * Test attribute "closest_model_value"
     */
    public function testPropertyClosestModelValue()
    {
    }

    /**
     * Test attribute "closest_model_color"
     */
    public function testPropertyClosestModelColor()
    {
    }

    /**
     * Test attribute "closest_model_activity"
     */
    public function testPropertyClosestModelActivity()
    {
    }

    /**
     * Test attribute "closest_model_top_tolerance"
     */
    public function testPropertyClosestModelTopTolerance()
    {
    }

    /**
     * Test attribute "closest_model_bottom_tolerance"
     */
    public function testPropertyClosestModelBottomTolerance()
    {
    }

    /**
     * Test attribute "day_model_name"
     */
    public function testPropertyDayModelName()
    {
    }

    /**
     * Test attribute "day_model_value"
     */
    public function testPropertyDayModelValue()
    {
    }

    /**
     * Test attribute "day_model_color"
     */
    public function testPropertyDayModelColor()
    {
    }

    /**
     * Test attribute "day_model_activity"
     */
    public function testPropertyDayModelActivity()
    {
    }

    /**
     * Test attribute "day_model_top_tolerance"
     */
    public function testPropertyDayModelTopTolerance()
    {
    }

    /**
     * Test attribute "day_model_bottom_tolerance"
     */
    public function testPropertyDayModelBottomTolerance()
    {
    }

    /**
     * Test attribute "day_prevision_model_name"
     */
    public function testPropertyDayPrevisionModelName()
    {
    }

    /**
     * Test attribute "day_prevision_model_value"
     */
    public function testPropertyDayPrevisionModelValue()
    {
    }

    /**
     * Test attribute "day_prevision_model_color"
     */
    public function testPropertyDayPrevisionModelColor()
    {
    }

    /**
     * Test attribute "day_prevision_model_activity"
     */
    public function testPropertyDayPrevisionModelActivity()
    {
    }

    /**
     * Test attribute "day_prevision_model_top_tolerance"
     */
    public function testPropertyDayPrevisionModelTopTolerance()
    {
    }

    /**
     * Test attribute "day_prevision_model_bottom_tolerance"
     */
    public function testPropertyDayPrevisionModelBottomTolerance()
    {
    }
}
