<?php
/**
 * AlertDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TimelightAi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * timelight
 *
 * This is the timelight api.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace TimelightAi;

/**
 * AlertDtoTest Class Doc Comment
 *
 * @category    Class
 * @description AlertDto
 * @package     TimelightAi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AlertDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AlertDto"
     */
    public function testAlertDto()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "source_id"
     */
    public function testPropertySourceId()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "criticity"
     */
    public function testPropertyCriticity()
    {
    }

    /**
     * Test attribute "shape"
     */
    public function testPropertyShape()
    {
    }

    /**
     * Test attribute "activity"
     */
    public function testPropertyActivity()
    {
    }

    /**
     * Test attribute "better_model_id"
     */
    public function testPropertyBetterModelId()
    {
    }

    /**
     * Test attribute "closest_model_id"
     */
    public function testPropertyClosestModelId()
    {
    }

    /**
     * Test attribute "favorite"
     */
    public function testPropertyFavorite()
    {
    }
}
