<?php
/**
 * ModelDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TimelightAi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * timelight
 *
 * This is the timelight api.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace TimelightAi;

/**
 * ModelDtoTest Class Doc Comment
 *
 * @category    Class
 * @description ModelDto
 * @package     TimelightAi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ModelDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ModelDto"
     */
    public function testModelDto()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "color"
     */
    public function testPropertyColor()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "activity"
     */
    public function testPropertyActivity()
    {
    }

    /**
     * Test attribute "top_tolerance"
     */
    public function testPropertyTopTolerance()
    {
    }

    /**
     * Test attribute "bottom_tolerance"
     */
    public function testPropertyBottomTolerance()
    {
    }

    /**
     * Test attribute "x"
     */
    public function testPropertyX()
    {
    }

    /**
     * Test attribute "y"
     */
    public function testPropertyY()
    {
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
    }

    /**
     * Test attribute "anomaly"
     */
    public function testPropertyAnomaly()
    {
    }
}
