<?php
/**
 * SourceDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TimelightAi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * timelight
 *
 * This is the timelight api.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace TimelightAi;

/**
 * SourceDtoTest Class Doc Comment
 *
 * @category    Class
 * @description SourceDto
 * @package     TimelightAi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SourceDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SourceDto"
     */
    public function testSourceDto()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "group_id"
     */
    public function testPropertyGroupId()
    {
    }

    /**
     * Test attribute "group_inertia"
     */
    public function testPropertyGroupInertia()
    {
    }

    /**
     * Test attribute "projection_x"
     */
    public function testPropertyProjectionX()
    {
    }

    /**
     * Test attribute "projection_y"
     */
    public function testPropertyProjectionY()
    {
    }

    /**
     * Test attribute "reference_year"
     */
    public function testPropertyReferenceYear()
    {
    }

    /**
     * Test attribute "has_prevision"
     */
    public function testPropertyHasPrevision()
    {
    }

    /**
     * Test attribute "prevision_enabled"
     */
    public function testPropertyPrevisionEnabled()
    {
    }

    /**
     * Test attribute "latitude"
     */
    public function testPropertyLatitude()
    {
    }

    /**
     * Test attribute "longitude"
     */
    public function testPropertyLongitude()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "alert_min_criticity"
     */
    public function testPropertyAlertMinCriticity()
    {
    }

    /**
     * Test attribute "alert_max_criticity"
     */
    public function testPropertyAlertMaxCriticity()
    {
    }
}
