<?php
/**
 * AIApiTest
 * PHP version 5
 *
 * @category Class
 * @package  TimelightAi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * timelight
 *
 * This is the timelight api.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace TimelightAi;

use \TimelightAi\Configuration;
use \TimelightAi\ApiException;
use \TimelightAi\ObjectSerializer;

/**
 * AIApiTest Class Doc Comment
 *
 * @category Class
 * @package  TimelightAi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AIApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for v1AiAnomaliesSourceIdGet
     *
     * Auto detect-anomalies.
     *
     */
    public function testV1AiAnomaliesSourceIdGet()
    {
    }

    /**
     * Test case for v1AiRecomputeDayModelsSourceIdYearPost
     *
     * Recomputes all day modesl.
     *
     */
    public function testV1AiRecomputeDayModelsSourceIdYearPost()
    {
    }

    /**
     * Test case for v1AiRecomputeDaysProjectionSourceIdYearPost
     *
     * Computes all days projection for a source and save them.
     *
     */
    public function testV1AiRecomputeDaysProjectionSourceIdYearPost()
    {
    }

    /**
     * Test case for v1AiRecomputeModelsSourceIdYearPost
     *
     * Triggers a model recompute.
     *
     */
    public function testV1AiRecomputeModelsSourceIdYearPost()
    {
    }

    /**
     * Test case for v1AiRecomputeSourceModelsModelCountPost
     *
     * Triggers a model recompute for source groups.
     *
     */
    public function testV1AiRecomputeSourceModelsModelCountPost()
    {
    }
}
