<?php
/**
 * DayContextApiTest
 * PHP version 5
 *
 * @category Class
 * @package  TimelightAi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * timelight
 *
 * This is the timelight api.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace TimelightAi;

use \TimelightAi\Configuration;
use \TimelightAi\ApiException;
use \TimelightAi\ObjectSerializer;

/**
 * DayContextApiTest Class Doc Comment
 *
 * @category Class
 * @package  TimelightAi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DayContextApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for v1DayContextBulkPost
     *
     * Create many DayContext.
     *
     */
    public function testV1DayContextBulkPost()
    {
    }

    /**
     * Test case for v1DayContextGet
     *
     * Retrieve many DayContext.
     *
     */
    public function testV1DayContextGet()
    {
    }

    /**
     * Test case for v1DayContextIdDelete
     *
     * Delete one DayContext.
     *
     */
    public function testV1DayContextIdDelete()
    {
    }

    /**
     * Test case for v1DayContextIdGet
     *
     * Retrieve one DayContext.
     *
     */
    public function testV1DayContextIdGet()
    {
    }

    /**
     * Test case for v1DayContextIdPatch
     *
     * Update one DayContext.
     *
     */
    public function testV1DayContextIdPatch()
    {
    }

    /**
     * Test case for v1DayContextIdPut
     *
     * Replace one DayContext.
     *
     */
    public function testV1DayContextIdPut()
    {
    }

    /**
     * Test case for v1DayContextImportMeteoCsvSourceIdPost
     *
     * Imports a meteo csv file for the source id.
     *
     */
    public function testV1DayContextImportMeteoCsvSourceIdPost()
    {
    }

    /**
     * Test case for v1DayContextPost
     *
     * Create one DayContext.
     *
     */
    public function testV1DayContextPost()
    {
    }
}
