<?php
/**
 * PrevisionApiTest
 * PHP version 5
 *
 * @category Class
 * @package  TimelightAi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * timelight
 *
 * This is the timelight api.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace TimelightAi;

use \TimelightAi\Configuration;
use \TimelightAi\ApiException;
use \TimelightAi\ObjectSerializer;

/**
 * PrevisionApiTest Class Doc Comment
 *
 * @category Class
 * @package  TimelightAi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PrevisionApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for v1PrevisionGroupApplyPrevisionPost
     *
     * Apply a source prevision to the whole group.
     *
     */
    public function testV1PrevisionGroupApplyPrevisionPost()
    {
    }

    /**
     * Test case for v1PrevisionListSourceIdYearGet
     *
     * Fetch data previsions for a given year.
     *
     */
    public function testV1PrevisionListSourceIdYearGet()
    {
    }

    /**
     * Test case for v1PrevisionSaveDefaultPrevisionsSourceIdYearPost
     *
     * Generate default previsions for the source and save them.
     *
     */
    public function testV1PrevisionSaveDefaultPrevisionsSourceIdYearPost()
    {
    }

    /**
     * Test case for v1PrevisionSavePost
     *
     * Save many previsions at once.
     *
     */
    public function testV1PrevisionSavePost()
    {
    }

    /**
     * Test case for v1PrevisionUpdatePatch
     *
     * Update a specific prevision.
     *
     */
    public function testV1PrevisionUpdatePatch()
    {
    }
}
