<?php
/**
 * SourceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  TimelightAi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * timelight
 *
 * This is the timelight api.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace TimelightAi;

use \TimelightAi\Configuration;
use \TimelightAi\ApiException;
use \TimelightAi\ObjectSerializer;

/**
 * SourceApiTest Class Doc Comment
 *
 * @category Class
 * @package  TimelightAi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SourceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for v1SourceListGet
     *
     * All user sources.
     *
     */
    public function testV1SourceListGet()
    {
    }

    /**
     * Test case for v1SourceSourceIdDelete
     *
     * Delete a source and all linked data.
     *
     */
    public function testV1SourceSourceIdDelete()
    {
    }

    /**
     * Test case for v1SourceSourceIdGroupPatch
     *
     * Update a source group.
     *
     */
    public function testV1SourceSourceIdGroupPatch()
    {
    }

    /**
     * Test case for v1SourceSourceIdPatch
     *
     * Update a source.
     *
     */
    public function testV1SourceSourceIdPatch()
    {
    }
}
