<?php
/**
 * UserApiTest
 * PHP version 5
 *
 * @category Class
 * @package  TimelightAi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * timelight
 *
 * This is the timelight api.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace TimelightAi;

use \TimelightAi\Configuration;
use \TimelightAi\ApiException;
use \TimelightAi\ObjectSerializer;

/**
 * UserApiTest Class Doc Comment
 *
 * @category Class
 * @package  TimelightAi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for v1UserLoginPost
     *
     * Log the user in.
     *
     */
    public function testV1UserLoginPost()
    {
    }

    /**
     * Test case for v1UserMeGet
     *
     * Retrieve current user information.
     *
     */
    public function testV1UserMeGet()
    {
    }

    /**
     * Test case for v1UserRegisterDemoPost
     *
     * .
     *
     */
    public function testV1UserRegisterDemoPost()
    {
    }
}
